# Generated by Django 6.0.2 on 2026-02-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0002_alunosistema2_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunosistema2',
            name='matricula',
            field=models.CharField(default=0, max_length=10, unique=True, verbose_name='Matrícula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alunosistema2',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
    ]
