# Generated by Django 6.0.2 on 2026-02-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0003_alunosistema2_matricula_alter_alunosistema2_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunosistema2',
            name='cpf',
            field=models.CharField(default=0, max_length=11, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
