# Generated by Django 6.0.2 on 2026-02-16 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema_1', '0001_initial'),
        ('sistema_2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('carga_horaria', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('enviada_para_sistema1', models.BooleanField(default=False)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('aluno_sistema2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='sistema_2.alunosistema2')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='integracao.disciplina')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-data_lancamento'],
            },
        ),
        migrations.CreateModel(
            name='Vinculacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vinculacao', models.DateTimeField(auto_now_add=True)),
                ('aluno_sistema1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vinculo', to='sistema_1.alunosistema1')),
                ('aluno_sistema2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vinculo', to='sistema_2.alunosistema2')),
            ],
            options={
                'verbose_name': 'Vinculação',
                'verbose_name_plural': 'Vinculaçõess',
            },
        ),
    ]
