# Generated by Django 6.0.2 on 2026-02-18 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_da_disciplina', to='integracao.disciplina'),
        ),
    ]
