# Generated by Django 6.0.2 on 2026-02-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoSistema1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('matricula', models.CharField(blank=True, max_length=10, null=True, verbose_name='Matrícula')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('pendente', 'Pendente')], default='ativo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criando em')),
            ],
            options={
                'verbose_name': 'Usuário do Sistema 1',
                'verbose_name_plural': 'Usuários do Sistema 1',
                'ordering': ['nome'],
            },
        ),
    ]
