# Generated by Django 6.0.2 on 2026-02-21 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_1', '0003_alter_alunosistema1_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunosistema1',
            name='user',
        ),
    ]
