# Generated by Django 6.0.2 on 2026-02-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_1', '0004_remove_alunosistema1_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunosistema1',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
    ]
